-- SQLite

-- SELECT ALL AND SHOW ALL DATA

SELECT 
    C.NAME AS NAME,
    CAR.NAME AS CAR,
    E.NAME AS FUNCIONARIO,
    L.START_DATE AS DATA_DE_INICIO,
    L.END_DATE AS DATA_DE_FIM,
    L.TOTAL AS VALOR_TOTAL
FROM LOCATIONS L
JOIN CUSTOMERS C ON L.CUSTOMER_ID = C.ID
JOIN CARS CAR ON L.CAR_ID = CAR.ID
JOIN EMPLOYEES E ON L.EMPLOYEE_ID = E.ID;
